services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
      - /dev/snd:/dev/snd
    links:
      - mqtt
        #- influxdb

